# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9af5054b3852121bbf30f17ac04149e27fbff67e5731742290fc7e452204879ea23e518e2e4081fa81e8fb547ec62a3509dd65f30f6d028d98ae41f92808c5e

test:
  secret_key_base: a787b53688c6d4cd3944b8502e6bb653d32ca08e015822c29ea768ebfe0340b50f18bfab1bee5718d60127575771f8d619fddce5706a53dc0de25c831b9b0603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
